In [1]:
import pandas as pd

In [2]:
ikea = pd.read_csv('ikea.csv', sep=',')
ikea

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [7]:
ikea['InvoiceDate'] = pd.to_datetime(ikea['InvoiceDate'], dayfirst=True)
ikea['invoice_dt'] = ikea['InvoiceDate'].dt.date
ikea['time'] = ikea['InvoiceDate'].dt.time

In [8]:
ikea

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,invoice_dt,time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011-12-09,12:50:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011-12-09,12:50:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-09,12:50:00
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-09,12:50:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011-12-09,12:50:00

In [9]:
ikea = ikea.drop(columns=['InvoiceDate'])

In [10]:
ikea.columns = ['invoiceno', 'stockcode', 'desc', 'quantity', 'unitprice', 'custid', 'country', 'date', 'time']
ikea['custid'] = ikea['custid'].fillna(0)
ikea = ikea[['invoiceno', 'date', 'time', 'stockcode', 'desc', 'quantity', 'unitprice', 'custid', 'country']]

In [11]:
ikea

,invoiceno,date,time,stockcode,desc,quantity,unitprice,custid,country
0,536365,2010-12-01,08:26:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom
1,536365,2010-12-01,08:26:00,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom
2,536365,2010-12-01,08:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom
3,536365,2010-12-01,08:26:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom
4,536365,2010-12-01,08:26:00,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...,...
541904,581587,2011-12-09,12:50:00,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France
541905,581587,2011-12-09,12:50:00,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France
541906,581587,2011-12-09,12:50:00,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France
541907,581587,2011-12-09,12:50:00,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France
541908,581587,2011-12-09,12:50:00,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France

In [ ]:

ikea.to_csv('ikea_updated.csv')